### ISSUE TITLE
pip无法安装依赖库

### ISSUE THREAD

**Issue by zhangshuwei0516** [chenmozhijin/LDDC#1]
请问为什么pip安装依赖库的时候显示No such file or directory: 'requirements.txt'

**Comment by chenmozhijin** [comment]
需要先进入源代码的目录再执行`pip install -r requirements.txt`

**Comment by zhangshuwei0516** [comment]
好的谢谢

**Comment by zhangshuwei0516** [comment]
> 需要先进入源代码的目录再执行`pip install -r requirements.txt`

好的谢谢
