### ISSUE TITLE
歌词，本地匹配的优化建议

### ISSUE THREAD

**Issue by 906584305** [chenmozhijin/LDDC#10]
文件夹里每个歌曲都有lrc文件看着不太协调，可以试试做一个编辑歌曲内歌词的功能，比如用foobar2000可以直接编辑内容，可是修改起来不太方便，就像这样：
![屏幕截图 2024-09-18 161305](https://github.com/user-attachments/assets/154efce4-33b5-429a-96ba-c3ef9fb52f88)
如果弄个可以直接写入歌词的功能就太方便了！这样就可以省去lrc歌词文件了（强迫症
本地匹配好像只能搜索文件夹内的所有音乐，如果只匹配几首就不太方便，建议添加单个曲子的匹配功能

**Comment by chenmozhijin** [comment]
已在[v0.8.0](https://github.com/chenmozhijin/LDDC/releases/tag/v0.8.0)中实现
