### ISSUE TITLE
请问一下lyric转换ass的时候变成两行重复可能是因为什么问题?

### ISSUE THREAD

**Issue by flywolf53** [chenmozhijin/LDDC#11]
![Snipaste_2024-09-19_05-32-17](https://github.com/user-attachments/assets/b5ab561f-b70f-4da2-b362-59aad7daaac7)

**Comment by flywolf53** [comment]
![Snipaste_2024-09-19_09-48-27](https://github.com/user-attachments/assets/7b65e047-dfd6-4505-9e9e-f35c65781573)
我发现不管哪首歌都这样,想着不知道是不是我哪里没设置好

**Comment by chenmozhijin** [comment]
已在[v0.7.2](https://github.com/chenmozhijin/LDDC/releases/tag/v0.7.2)中修复
