### ISSUE TITLE
Deepin 23 系统 无法输入中文 

### ISSUE THREAD

**Issue by sbfwfnh** [chenmozhijin/LDDC#15]
Deepin 23 系统 无法输入中文

**Comment by chenmozhijin** [comment]
这应该是由于PySide(Qt)不支持fcitx输入法框架导致的，linux所有使用fcitx框架输入法都无法使用，我尝试在LDDC最新测试版(0.8.0-alpha.1)中添加了fcitx插件,我在ubuntu 24中使用Fcitx5与谷歌拼音输入法测试了没有问题

LDDC(0.8.0-alpha.1)下载: [Linux - x64 artifacts](https://github.com/chenmozhijin/LDDC/actions/runs/11218417756/artifacts/2024594970)
![image](https://github.com/user-attachments/assets/10033abb-bb01-4959-84cf-9847b76930b8)

**Comment by chenmozhijin** [comment]
已在[v0.8.0](https://github.com/chenmozhijin/LDDC/releases/tag/v0.8.0)中修复
