### ISSUE TITLE
本地匹配超时的歌词会导致App整个卡死

### ISSUE THREAD

**Issue by KIY7086** [chenmozhijin/LDDC#16]
本地匹配模式每次匹配到超时的歌词就会卡死，只能退出App然后删掉超时的音乐文件
希望可以增加一个超时跳过的功能或者修复一下这个Bug

**Comment by chenmozhijin** [comment]
[v0.8.0](https://github.com/chenmozhijin/LDDC/releases/tag/v0.8.0)已发布，本地匹配相关代码已全部重构，没有测试到类似问题
