### ISSUE TITLE
遇到某个文件夹无法正常扫描

### ISSUE THREAD

**Issue by Ireseey** [chenmozhijin/LDDC#18]
![2024-10-21_17-09](https://github.com/user-attachments/assets/32ead558-2f21-42db-8f3c-300922f2fe5c)
![2024-10-21_17-10](https://github.com/user-attachments/assets/0f8e39d2-1492-44e7-ac19-43811e8b8e97)
平台linux，后续音乐会上传网盘

**Comment by Ireseey** [comment]
> ![2024-10-21_17-09](https://private-user-images.githubusercontent.com/130719514/378351294-32ead558-2f21-42db-8f3c-300922f2fe5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDIxNjgsIm5iZiI6MTcyOTUwMTg2OCwicGF0aCI6Ii8xMzA3MTk1MTQvMzc4MzUxMjk0LTMyZWFkNTU4LTJmMjEtNDJkYi04ZjNjLTMwMDkyMmYyZmU1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwOTExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWQyMDdkNWE1M2M3MDk1MWUwMzI2MWVkOTQ5MGNjZTllMThkYWUyOTZlY2JiNjU3NDBiZDBiMmZjYjFiNjg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vdyEDgqwcp9s0J30MFSftjM3ga6-jXW_mdoxwAdMfnA) ![2024-10-21_17-10](https://private-user-images.githubusercontent.com/130719514/378351587-0f8e39d2-1492-44e7-ac19-43811e8b8e97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDIxNjgsIm5iZiI6MTcyOTUwMTg2OCwicGF0aCI6Ii8xMzA3MTk1MTQvMzc4MzUxNTg3LTBmOGUzOWQyLTE0OTItNDRlNy1hYzE5LTQzODExZThiOGU5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwOTExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGI2N2M5ODkzMmFhMDAzOTU4ZGVlYTE3ODI4YmFkMTgyZmQxYmI0YTg2NjFhYzc1N2UzOGM4ZGY3ZGMwYjMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CqBx5EJS2HvR262jYgrqfd43prJ6LYs1ibjJq02YZMo) 平台linux，后续音乐会上传网盘

「Arte Refact」https://www.alipan.com/s/tNjJBFaZSXs
提取码: LBYj

**Comment by chenmozhijin** [comment]
能解释一下是怎么个不正常法吗？

**Comment by chenmozhijin** [comment]
[v0.8.0](https://github.com/chenmozhijin/LDDC/releases/tag/v0.8.0)已发布，本地匹配相关代码已全部重构，没有测试到类似问题

**Comment by Ireseey** [comment]
> [v0.8.0](https://github.com/chenmozhijin/LDDC/releases/tag/v0.8.0)已发布，本地匹配相关代码已全部重构，没有测试到类似问题
非常感谢，后续将进行测试
