### ISSUE TITLE
读取歌曲文件信息时错误

### ISSUE THREAD

**Issue by 125150045** [chenmozhijin/LDDC#19]
读取歌曲文件信息时错误:C:\Users\Administrator\Desktop\Music\银临 Aki阿杰 - 牵丝戏.flac 无法获取歌曲标题
没有找到可查找歌词的歌曲
![QQ20241025-210917](https://github.com/user-attachments/assets/c02b0085-8007-4145-8139-064336bf98df)

**Comment by chenmozhijin** [comment]
LDDC目前只通过歌曲标签来获取标题进行匹配，你的歌曲文件中没有歌曲标签或者标签中不包含标题就会报这个错。
