### ISSUE TITLE
一次只可以保存一次歌词？

### ISSUE THREAD

**Issue by bobohu123** [chenmozhijin/LDDC#21]
macbook 一次只可以保存一次歌词？保存之后app点了没任何反应 强制退出后 才可以重新搜索

**Comment by chenmozhijin** [comment]
下个版本修复
你可以先试试v0.8.0-alpha.2测试版
arm64: https://github.com/chenmozhijin/LDDC/actions/runs/11634813913/artifacts/2134500807
x64: https://github.com/chenmozhijin/LDDC/actions/runs/11634813913/artifacts/2134513457

**Comment by chenmozhijin** [comment]
这应该是[Nuitka](https://github.com/Nuitka/Nuitka)的问题(现在好像已经修复了?)，直接使用python运行源码是没有这个问题的

你可以试试最新测试版，应该没有这个问题
arm64: https://github.com/chenmozhijin/LDDC/actions/runs/11634813913/artifacts/2134500807
x64: https://github.com/chenmozhijin/LDDC/actions/runs/11634813913/artifacts/2134513457

**Comment by chenmozhijin** [comment]
已在[v0.8.0](https://github.com/chenmozhijin/LDDC/releases/tag/v0.8.0)中修复
