### ISSUE TITLE
无法获取歌单

### ISSUE THREAD

**Issue by y1zh3e7** [chenmozhijin/LDDC#3]
大佬，我在获取歌词时选中了我自己的歌单，但是报错了，是网易云那边接口改了吗
<img width="716" alt="image" src="https://github.com/chenmozhijin/LDDC/assets/103484908/993a7244-e144-47a0-84f2-3024127b46cf">

**Comment by chenmozhijin** [comment]
已在[v0.6.0版本](https://github.com/chenmozhijin/LDDC/releases/tag/v0.6.0)中修复
